- name: Validate prometheus_action_list
  ansible.builtin.assert:
    that:
      - prometheus_actions is defined
      - prometheus_actions is string
      - prometheus_actions | length > 0

- name: Create prometheus_action_list
  ansible.builtin.set_fact:
    prometheus_action_list: "{{ prometheus_actions.split(',') }}"

- name: Validate prometheus_action_list
  ansible.builtin.assert:
    that:
      - prometheus_action_list | length > 0
      - prometheus_action_list | difference(prometheus_supported_actions) | length == 0

- name: Install prometheus
  when: "'install' in prometheus_action_list"
  ansible.builtin.include_tasks: install.yml

- name: Upload configuration files
  when: "'upload_config' in prometheus_action_list"
  ansible.builtin.include_tasks: upload_config.yml

- name: Control prometheus state
  when: "'state_control' in prometheus_action_list"
  ansible.builtin.include_tasks: state_control.yml
